version: "3.4"
services:
  golang: #docker run -it -v ${PWD}:/go/src/work -v ${PWD}/golang/configs/:/configs -v ${PWD}/golang/secrets/:/secrets  -p 5001:5000 -p 2345:2345 --security-opt "seccomp:unconfined" aimvector/golang:1.0.0
    container_name: golang
    image: proy/golang:1.0.0
    build: 
      context: ./golang
      target: debug
    volumes:
    - ./golang/configs:/configs/
    - ./golang/secrets:/secrets/
    - ./golang/src/:/go/src/work/
    ports:
      - 5001:5000
      - 2345:2345
    security_opt:
      - "seccomp:unconfined"